[package]
name = "book-archive-service"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
reqwest = { version = "0.12", features = ["json"] }

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["handlebars", "tera", "minijinja"]